### ISSUE TITLE
Error with jQuery 1.4.2

### ISSUE THREAD

**Issue by bob6664569** [timmywil/password123#1]
Webkit Error : "Uncaught TypeError: Cannot read property 'nodeType' of null" in jquery.js

From $.fn.password123 -> $.fn.textchange -> jQuery.fn.name -> jQuery.event.add [x]

Part of code :
    $.fn['textchange'] = function (fn) {
        return fn ? this.bind('textchange', fn) : this.trigger('textchange'); // -- Error triggered by "this.bind('textchange', fn)"
    };

**Comment by timmywil** [comment]
I am unable to reproduce this error.  Can you provide a test case?
