### ISSUE TITLE
destroy function

### ISSUE THREAD

**Issue by nickmay** [timmywil/password123#3]
Hi

Love this plugin - works very well. Is it possible to "unbind" the plugin programmatically, then rebind it? I want to give users the option to switch it on and off, depending on whether they want its functionality in the environment they are in (i.e., in public they maybe don't want it...)

Is there a destroy function? If not, this would be a great thing to add...

kind regards

**Comment by timmywil** [comment]
Excellent idea.  I will add a destroy function.
